"""Deterministic Markdown reporting for exact Mark Six prize probabilities."""

from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal, localcontext
from fractions import Fraction
from pathlib import Path

from mark_six.domain.rules import RULE_VERSIONS
from mark_six.mathematics.combinatorics import (
    OutcomeOdds,
    prize_outcome_odds,
    probability_of_any_prize,
)
from mark_six.mathematics.payouts import CURRENT_FIXED_PRIZES_HKD_CENTS
from mark_six.mathematics.prize_fund import (
    FIRST_DIVISION_SHARE,
    HKJC_COMMISSION_SHARE,
    LOTTERIES_FUND_SHARE,
    LOTTERY_DUTY_SHARE,
    PRIZE_FUND_SHARE,
    SECOND_DIVISION_SHARE,
    THIRD_DIVISION_SHARE,
)

OFFICIAL_FIRST_DIVISION_ONE_IN = 13_983_816


@dataclass(frozen=True)
class MathematicalModel:
    """A pool/division model and the rule versions to which it may apply."""

    label: str
    pool_size: int
    prize_divisions: int
    rule_version_ids: tuple[str, ...]
    evidence_note: str


MATHEMATICAL_MODELS = (
    MathematicalModel(
        label="Historical 6/45 candidate",
        pool_size=45,
        prize_divisions=6,
        rule_version_ids=(
            "hkjc_mark_six_1993_to_1994_partial",
            "hkjc_mark_six_1995_stake4_transition_unresolved",
            "hkjc_mark_six_1995_stake5_transition_unresolved",
            "hkjc_mark_six_1996_pool_transition_unresolved",
        ),
        evidence_note=(
            "The 1993-1995 pool size is supported by official chronology and result records. "
            "For 1996 this is one candidate because the exact 45-to-47 boundary remains "
            "unresolved. "
            "Six-division qualification and Extra Number mechanics are conditional pending "
            "contemporaneous formal rules."
        ),
    ),
    MathematicalModel(
        label="Historical 6/47 candidate",
        pool_size=47,
        prize_divisions=6,
        rule_version_ids=(
            "hkjc_mark_six_1996_pool_transition_unresolved",
            "hkjc_mark_six_1997_to_2002_07_02_partial",
        ),
        evidence_note=(
            "The 1997-to-2002-07-02 pool size is supported by official chronology and result "
            "records. For 1996 this is the other candidate. Six-division qualification and Extra "
            "Number mechanics are conditional pending contemporaneous formal rules."
        ),
    ),
    MathematicalModel(
        label="Current-form 6/49",
        pool_size=49,
        prize_divisions=7,
        rule_version_ids=(
            "hkjc_mark_six_2002_07_03_partial",
            "hkjc_mark_six_2010_11_09_partial",
            "hkjc_mark_six_2024_05_21",
        ),
        evidence_note=(
            "The 6/49 boundary and Seventh Prize introduction are dated to 2002-07-03. Current "
            "qualifications and Extra Number mechanics are formally verified; applying identical "
            "qualifications throughout earlier partial intervals remains conditional on their "
            "incomplete historical rule evidence."
        ),
    ),
)


def _fraction_text(value: Fraction) -> str:
    return f"{value.numerator}/{value.denominator}"


def _decimal_text(value: Fraction, places: int = 12) -> str:
    with localcontext() as context:
        context.prec = 40
        decimal = Decimal(value.numerator) / Decimal(value.denominator)
    return f"{decimal:.{places}f}"


def _one_in_text(value: Fraction) -> str:
    if value.denominator == 1:
        return f"1 in {value.numerator:,}"
    return f"1 in {_decimal_text(value, 6)} (exactly {_fraction_text(value)})"


def _hkd_text(cents: Fraction) -> str:
    return f"HKD {_decimal_text(cents / 100, 6)} (exactly {_fraction_text(cents)} cents)"


def _table(odds: tuple[OutcomeOdds, ...]) -> list[str]:
    lines = [
        "| Outcome | Winning combinations | Exact probability | Decimal probability | Odds "
        "| Derivation |",
        "|---|---:|---:|---:|---:|---|",
    ]
    for item in odds:
        label = item.outcome.replace("_", " ").title()
        lines.append(
            f"| {label} | {item.winning_combinations:,} | `{_fraction_text(item.probability)}` "
            f"| {_decimal_text(item.probability)} | {_one_in_text(item.one_in)} "
            f"| `{item.derivation}` |"
        )
    return lines


def render_prize_probability_report() -> str:
    """Render the complete report without reading draw outcomes or using randomness."""

    current_odds = prize_outcome_odds(49, 7)
    first = current_odds[0]
    official_matches = first.one_in == OFFICIAL_FIRST_DIVISION_ONE_IN
    lines = [
        "# Exact Mark Six Prize Probabilities",
        "",
        "**Generated by:** `mark-six mathematics prize-probabilities`  ",
        "**Arithmetic:** exact integers and rational fractions; no simulation  ",
        "**Scope:** rule mathematics only; no draw-frequency or predictive analysis",
        "",
        "## Method",
        "",
        "Fix six main numbers and one distinct Extra Number from a pool of `N`. Every ordinary "
        "ticket is one of `C(N,6)` equally likely six-number sets. Each row below counts tickets "
        "with the required main-number overlap and Extra Number inclusion. Rows are mutually "
        "exclusive. `No Prize` is the exact complement of the applicable prize rows.",
        "",
        "## Current 6/49, seven-division model",
        "",
        *_table(current_odds),
        "",
        f"Exact probability sum including No Prize: `1/1`. Total ticket universe: "
        f"`C(49,6) = {sum(item.winning_combinations for item in current_odds):,}`.",
        "",
        "## Independent official check",
        "",
        "HKJC publishes First Division odds of 1 in 13,983,816. The independently derived value "
        f"is {_one_in_text(first.one_in)}: **{'MATCH' if official_matches else 'DIFFERENCE'}**. "
        "No rounding is involved in this comparison. Current HKJC prize-qualification material "
        "also independently confirms the seven mutually exclusive winning patterns used above.",
        "",
        "Official sources:",
        "",
        "- [HKJC Mark Six fun facts (published First Division odds)]"
        "(https://campaigns.hkjc.com/2026-marksix/en/funfacts)",
        "- [HKJC prize qualifications]"
        "(https://special.hkjc.com/e-win/en-US/betting-info/marksix/prize-qualification/)",
        "- [HKJC Multiple and Banker chance table]"
        "(https://special.hkjc.com/e-win/en-US/betting-info/marksix/chance-table/)",
        "",
        "## Rule-version model catalogue",
        "",
        "These tables are mathematical consequences of the stated pool and qualification model. "
        "They do not turn an unresolved historical boundary or unverified historical prize rule "
        "into a fact.",
        "",
    ]
    for model in MATHEMATICAL_MODELS:
        odds = prize_outcome_odds(model.pool_size, model.prize_divisions)
        lines.extend(
            (
                f"### {model.label}",
                "",
                model.evidence_note,
                "",
                "Rule registry mappings:",
                "",
                *(f"- `{rule_id}`" for rule_id in model.rule_version_ids),
                "",
                *_table(odds),
                "",
                f"Exact probability sum including No Prize: `1/1`. Total ticket universe: "
                f"`C({model.pool_size},6) = "
                f"{sum(item.winning_combinations for item in odds):,}`.",
                "",
            )
        )
    registry_ids = set(RULE_VERSIONS)
    mapped_ids = {rule_id for model in MATHEMATICAL_MODELS for rule_id in model.rule_version_ids}
    if mapped_ids != registry_ids:
        raise RuntimeError("mathematical model mapping must cover the complete rule registry")
    lines.extend(
        (
            "## Interpretation limits",
            "",
            "- `hkjc_mark_six_1996_pool_transition_unresolved` deliberately maps to both the 6/45 "
            "and 6/47 candidate tables. A draw-level calculation in 1996 must not choose between "
            "them without evidence of the applicable pool.",
            "- Historical tables assume the same six-main/one-Extra qualification patterns shown. "
            "The registry's partial-verification status remains authoritative where archived "
            "formal rules have not been located.",
            "- Multiple and Banker entries are collections of unique ordinary combinations. Their "
            "First Division probability is covered combinations divided by `C(N,6)`; shared-number "
            "tickets are not treated as independent events.",
            "- Prize probability is separate from payout. Divisions 1-3 are variable under current "
            "rules; fixed values and supplied dividends belong in the payout model, not in these "
            "probability calculations.",
            "",
        )
    )
    return "\n".join(lines)


def write_prize_probability_report(path: Path) -> Path:
    """Write the deterministic probability report and return its path."""

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_prize_probability_report(), encoding="utf-8")
    return path


def render_current_game_mathematics_report() -> str:
    """Render the current-game report from exact rule mathematics."""

    odds = prize_outcome_odds(49, 7)
    any_prize = probability_of_any_prize(49, 7)
    fixed_expected = sum(
        (
            odds[division - 1].probability * prize
            for division, prize in CURRENT_FIXED_PRIZES_HKD_CENTS.items()
        ),
        Fraction(),
    )
    return "\n".join(
        [
            "# Current Mark Six Game Mathematics",
            "",
            "**Evidence:** official current rules plus exact combinatorial derivation  ",
            "**Scope:** fair-draw mathematics only; no historical-number or predictive analysis",
            "",
            "## Current game",
            "",
            "HKJC's current rules use numbers 1-49. Six main numbers are drawn without "
            "replacement, followed by one Extra Number from the remaining 43. An ordinary "
            "ticket contains six distinct numbers. Therefore every valid combination is one of "
            "`C(49,6) = 13,983,816` equally likely sets.",
            "",
            *_table(odds),
            "",
            f"Probability of winning any prize: `{_fraction_text(any_prize)}` = "
            f"`{_decimal_text(any_prize)}` ({_one_in_text(1 / any_prize)}).",
            "",
            "The exact probability partition, including No Prize, is `1/1`. The independently "
            "derived First Division odds are exactly 1 in 13,983,816, matching HKJC's published "
            "figure without rounding.",
            "",
            "## Stakes and fixed prizes",
            "",
            "The verified normal unit is HKD 10. A HKD 5 partial unit is accepted only for "
            "Multiple and Banker entries and receives the same one-half scaling of prizes. "
            "Current fixed full-unit prizes are HKD 9,600, HKD 640, HKD 320, and HKD 40 for "
            "Divisions 4-7. Their combined exact expected contribution to one ordinary full-unit "
            f"ticket is {_hkd_text(fixed_expected)}. Divisions 1-3 are variable and are not "
            "silently assigned a value.",
            "",
            "## Multiple entries",
            "",
            "Selecting `s` numbers produces every unique six-number subset: `C(s,6)` ordinary "
            "combinations. Cost equals that count times the applicable unit stake. First Division "
            "coverage is `C(s,6) / C(49,6)`. An eight-number Multiple has 28 combinations; if it "
            "contains all six main numbers but not Extra, it wins one First, 12 Third, and 15 "
            "Fifth Division prizes simultaneously.",
            "",
            "## Banker entries",
            "",
            "For `b` bankers and `l` legs, each ticket includes all bankers and chooses `6-b` "
            "legs, producing `C(l,6-b)` unique combinations. A two-banker, five-leg entry produces "
            "five combinations. Its First Division probability is exactly "
            "`5 / 13,983,816`, identical to any other purchase covering five distinct ordinary "
            "combinations.",
            "",
            "## Coverage is not prediction",
            "",
            "Buying more distinct combinations increases the fraction of the outcome space "
            "covered and increases cost in the same linear way. It does not change the probability "
            "of any individual valid combination. Under the fair-draw model, labels on balls have "
            "no mathematical preference: every six-number set has probability `1 / C(49,6)`.",
            "",
            "## Evidence labels",
            "",
            "- Pool, draw mechanics, stakes, qualifications, and fixed amounts: **official "
            "rule-based calculation**.",
            "- Counts, fractions, and coverage formulas: **exact combinatorial result**.",
            "- Decimal probabilities: exact fractions displayed in decimal form, not simulation.",
            "- No economic or behavioral assumption is used in this report.",
            "",
            "Official sources:",
            "",
            "- [HKJC prize qualifications]"
            "(https://special.hkjc.com/e-win/en-US/betting-info/marksix/prize-qualification/)",
            "- [HKJC entry types]"
            "(https://special.hkjc.com/e-win/en-US/betting-info/marksix/types-of-entry/)",
            "- [HKJC chance table]"
            "(https://special.hkjc.com/e-win/en-US/betting-info/marksix/chance-table/)",
            "- [HKJC 2026 fun facts (published First Division odds)]"
            "(https://campaigns.hkjc.com/2026-marksix/en/funfacts)",
            "",
        ]
    )


def render_expected_value_foundation_report() -> str:
    """Render exact EV foundations while exposing every future economic assumption."""

    odds = prize_outcome_odds(49, 7)
    fixed_lines = [
        "| Division | Exact probability | Fixed full-unit prize | Exact EV contribution |",
        "|---:|---:|---:|---:|",
    ]
    fixed_total = Fraction()
    for division, amount in CURRENT_FIXED_PRIZES_HKD_CENTS.items():
        contribution = odds[division - 1].probability * amount
        fixed_total += contribution
        fixed_lines.append(
            f"| {division} | `{_fraction_text(odds[division - 1].probability)}` "
            f"| HKD {_decimal_text(Fraction(amount, 100), 2)} | {_hkd_text(contribution)} |"
        )
    return "\n".join(
        [
            "# Expected Value Foundation",
            "",
            "**Purpose:** define auditable payout inputs; not estimate a future jackpot return  ",
            "**Arithmetic:** exact rational HKD cents until a documented payout-rounding rule "
            "applies",
            "",
            "## Meaning of expected value",
            "",
            "Expected payout per ticket is the sum, over mutually exclusive prize outcomes, of "
            "`probability * dividend`. Net expected value additionally subtracts ticket cost. An "
            "exact probability does not make an unknown future dividend exact.",
            "",
            "## Fixed components",
            "",
            *fixed_lines,
            "",
            f"Combined fixed-prize expected payout: {_hkd_text(fixed_total)} per full-unit "
            "ordinary ticket. This combines exact combinatorial probabilities with official "
            "fixed prizes.",
            "",
            "## Turnover and Prize Fund",
            "",
            f"Under current official material, 54% (`{_fraction_text(PRIZE_FUND_SHARE)}`) of "
            "turnover enters the Prize Fund. The remaining turnover is separately allocated as "
            f"25% (`{_fraction_text(LOTTERY_DUTY_SHARE)}`) Lottery Duty, "
            f"15% (`{_fraction_text(LOTTERIES_FUND_SHARE)}`) to the Lotteries Fund, and "
            f"6% (`{_fraction_text(HKJC_COMMISSION_SHARE)}`) HKJC Lotteries Limited commission. "
            "These four shares sum exactly to one and are not interchangeable concepts.",
            "",
            "Let `P` be the Prize Fund and `F` the total amount payable to fixed Divisions 4-7. "
            "For the standard current case `F <= 60% P`, the published Snowball Deduction is:",
            "",
            "`S = 9% * [P - F - 55% * (60% * P - F)] + 55% * (60% * P - F)`",
            "",
            "The current variable pool is `V = P - F - S`, excluding any carried Jackpot or "
            "Snowball addition. Its official starting allocations are:",
            "",
            f"- First Division: `{_fraction_text(FIRST_DIVISION_SHARE)} * V`",
            f"- Second Division: `{_fraction_text(SECOND_DIVISION_SHARE)} * V`",
            f"- Third Division: `{_fraction_text(THIRD_DIVISION_SHARE)} * V`",
            "",
            "These percentages may be adjusted under the formal minimum-prize hierarchy. If fixed "
            "prizes exceed 60% of the Prize Fund, Rule 3.16 invokes exceptional Snowball funding "
            "and potentially rateable reductions. The implementation rejects use of the standard "
            "formula in that state rather than returning a misleading negative deduction.",
            "",
            "## Minimum, sharing, and rollover",
            "",
            "The currently published minimum First Division Prize Fund is HKD 8 million. The "
            "minimum helper reports the exact Snowball top-up and any unmet shortfall separately; "
            "an insufficient Snowball balance is not hidden. For a variable division with a "
            "positive number of winning units, dividend before documented rounding is "
            "`division fund / winning units`.",
            "",
            "If First Division has no winner, its fund carries to the next draw's First Division. "
            "If Second has no winner, its fund also carries to the next First Division. If Third "
            "has no winner, its fund is reallocated 75%/25% to First/Second when both have "
            "winners, entirely to the one that has winners, or carried to the next First Division "
            "when neither has winners. The exact sharing helper supports downward rounding to a "
            "supplied Unit Stake Amount and exposes the rounding surplus. A sole partial-unit "
            "winner still requires the special Rule 3.10 branch and is rejected by the ordinary "
            "sharing path.",
            "",
            "## Explicit variable-payout inputs",
            "",
            "The EV API requires callers to provide the available variable pool, exact First/"
            "Second/Third allocation shares, winning units, carried Jackpot, Snowball "
            "contribution, and special-jackpot contribution. Contributions remain separately "
            "named even though they "
            "ultimately supplement First Division. A source amount must not be entered twice under "
            "different labels.",
            "",
            "The code predicts none of these inputs. In a future draw, prize-pool inputs are "
            "**economic assumptions** and other-player winning units are **behavioral "
            "assumptions**. For a completed historical draw, the same quantities may instead be "
            "official source observations if provenance and publication timing are verified.",
            "",
            "## Why jackpot size is insufficient",
            "",
            "An advertised jackpot alone does not specify turnover, fixed-prize liability, "
            "Snowball Deduction, actual First Division fund, number and stake size of winning "
            "units, rounding surplus, or the ticket's cost. Multiple First Division winning units "
            "divide the fund. Therefore no positive expected-value claim follows from jackpot "
            "size alone.",
            "",
            "## Data needed in a later phase",
            "",
            "- Time-stamped pre-draw turnover or pool estimates and their revision history.",
            "- Provenance-resolved carried Jackpot, Snowball balance/addition, and special-jackpot "
            "amounts without double counting.",
            "- Winning-unit and partial-unit distributions, or an explicitly pre-registered model "
            "for future prize sharing.",
            "- Complete operational inputs for minimum-prize adjustments and exceptional Rule "
            "3.16 funding, plus winner composition needed to apply Rules 3.10 and 3.17 correctly.",
            "- Ticket sales and player-choice data before any behavioral model is considered. "
            "Phase 4 does not optimize number choices using player behavior.",
            "",
            "## Evidence labels",
            "",
            "| Quantity | Label |",
            "|---|---|",
            "| Prize probabilities | Exact combinatorial result |",
            "| Current percentages, fixed prizes, minimum, rollover formulas "
            "| Official rule-based calculation |",
            "| Completed-draw source fields, once provenance-verified "
            "| Historical source observation |",
            "| Monte Carlo output | Simulation estimate; never used as the EV source of truth |",
            "| Future pool, turnover, or contribution inputs | Economic assumption |",
            "| Future other-player winning units | Behavioral assumption |",
            "",
            "Official sources:",
            "",
            "- [HKJC prize allocation]"
            "(https://special.hkjc.com/e-win/en-US/betting-info/marksix/allocation-of-prize-fund/)",
            "- [HKJC prize qualifications and fixed prizes]"
            "(https://special.hkjc.com/e-win/en-US/betting-info/marksix/prize-qualification/)",
            "- [HKJC 2010 restructuring notice]"
            "(https://www.hkjc.com/english/pressrelease/mcs01_showhtml.asp?"
            "filename=20100928_194443_E_NEWS.htm)",
            "",
        ]
    )


def write_mathematics_reports(project_root: Path) -> tuple[Path, ...]:
    """Write all deterministic Phase 4 Markdown reports."""

    report_dir = project_root / "reports" / "generated"
    outputs = (
        (report_dir / "prize_probabilities.md", render_prize_probability_report()),
        (report_dir / "current_game_mathematics.md", render_current_game_mathematics_report()),
        (report_dir / "expected_value_foundation.md", render_expected_value_foundation_report()),
    )
    for path, content in outputs:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return tuple(path for path, _ in outputs)
